<a href="https://colab.research.google.com/github/germanoisabela/DataScience/blob/main/Exemplos_Aula_09.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**# Exemplo de Pré-processamento de Dados (Titanic Dataset)**

In [14]:
#@title 1.Import da Bibliotecas

import pandas as pd
import numpy as np

from sklearn.preprocessing import (
    LabelEncoder,
    OneHotEncoder,
    StandardScaler,
    RobustScaler,
    MinMaxScaler,
    QuantileTransformer,
    PowerTransformer,
    Normalizer
)

from sklearn.decomposition import PCA
from sklearn.utils import resample

In [16]:
dados = pd.read_csv('Titanic-Dataset.csv')
display(dados.head())
print ("\n\n")
display(dados.tail())
print ("\n\n")
display(dados.sample(5))

   PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0            1         0       3  ...   7.2500   NaN         S
1            2         1       1  ...  71.2833   C85         C
2            3         1       3  ...   7.9250   NaN         S
3            4         1       1  ...  53.1000  C123         S
4            5         0       3  ...   8.0500   NaN         S

[5 rows x 12 columns]

     PassengerId  Survived  Pclass  ...   Fare Cabin  Embarked
886          887         0       2  ...  13.00   NaN         S
887          888         1       1  ...  30.00   B42         S
888          889         0       3  ...  23.45   NaN         S
889          890         1       1  ...  30.00  C148         C
890          891         0       3  ...   7.75   NaN         Q

[5 rows x 12 columns]

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
290          291         1       1  ...  78.8500   NaN         S
552          553         0       3  ...   7.8292   NaN         Q
768          769         0       3  ...  24.1500   NaN         Q
643          644         1       3  ...  56.4958   NaN         S
244          245         0       3  ...   7.2250   NaN         C

[5 rows x 12 columns]